# Copyright 2020 Pants project contributors.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

[GLOBAL]
pants_version = "2.4.0"
pantsd = true  # Enable the Pants daemon for better performance.

backend_packages.add = [
  "pants.backend.awslambda.python",
  "pants.backend.codegen.protobuf.python",
  "pants.backend.python",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
  # Adds the `py-constraints` goal, as this example repository has
  # both Python 2 and Python 3 code.
  "pants.backend.python.mixed_interpreter_constraints",
]

[source]
# The Python source root is the repo root. See https://www.pantsbuild.org/docs/source-roots.
root_patterns = ["/"]

##[python-infer]
##inits = true

[python-setup]
# The default interpreter compatibility for code in this repo. Individual targets can override
#  this with the `interpreter_constraints` field. See
#  https://www.pantsbuild.org/docs/python-interpreter-compatibility.
interpreter_constraints = [">=3.8,<3.9"]
# Use a constraints file. See https://www.pantsbuild.org/docs/python-third-party-dependencies.
requirement_constraints = "constraints.txt"
# We search for interpreters on both on the $PATH and in the `$(pyenv root)/versions` folder.
#  If you're using macOS, you may want to leave off the <PATH> entry to avoid using the
#  problematic system Pythons. See
#  https://www.pantsbuild.org/docs/python-interpreter-compatibility#changing-the-interpreter-search-path.
interpreter_search_paths = ["<PATH>", "<PYENV>"]

[python-protobuf]
# See https://www.pantsbuild.org/docs/protobuf.
runtime_dependencies = ["//:grpcio", "//:protobuf"]
mypy_plugin = true

[flake8]
config = "build-support/.flake8"

[isort]
config = [".isort.cfg"]

[mypy]
config = "build-support/mypy.ini"

[anonymous-telemetry]
enabled = true
repo_id = "83C8E4F3-E90C-4A98-89CD-6260AF4DB115"