# Copyright 2020 Pants project contributors.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# See https://www.pantsbuild.org/docs/using-pants-in-ci.

[GLOBAL]
pantsd = false

# Limit the maximum number of concurrent processes. Change this
# to a number that makes sense for your CI setup, based on
# the number of cores/threads.
process_execution_local_parallelism = 2

# Ref https://www.pantsbuild.org/docs/using-pants-in-ci

[GOBAL]
dynamic_ui = false
process_execution_local_parallelism = 4  
colors = true


[python-setup]
# Limit the maximum number of concurrent jobs used to resolve third
# party dependencies. The total level of parallelism will be
# `process_execution_local_parallelism x resolver_jobs`.
resolver_jobs = 2

[pytest]
args = ["-vv"]